//  Create a landing table
.create table landing(document:dynamic)

//  Create the mapping from JSON ingestion to landing table
.create table landing ingestion json mapping 'landingMapping' '[{"column":"document","path":"$","datatype":"dynamic"}]'

//  Alter retention policy as this is just the landing zone
.alter table landing policy retention "{'SoftDeletePeriod': '0:05:00', 'Recoverability':'Enabled'}"

//  Alter ingestion policy to ingest more often than default (5 minutes)
.alter table landing policy ingestionbatching "{'MaximumBatchingTimeSpan': '0:0:30'}"

//  Create the records table:  this is the strong-type version of ingestion
.create table deviceLog(
    deviceId:string,
    generationId:long,
    enqueuedTime:datetime,
    recordedAt:datetime,
    payload:string)

//  Alter retention policy as this is only for end-user queries
.alter table landing policy retention "{'SoftDeletePeriod': '0:15:00', 'Recoverability':'Enabled'}"

//  Function used to parse the log
.create-or-alter function parseDeviceLog(){
    landing
    | project deviceId=tostring(document['iothub-connection-device-id']),
        generationId=tolong(document['iothub-connection-auth-generation-id']),
        enqueuedTime=todatetime(document['iothub-enqueuedtime']),
        recordedAt=todatetime(document.recordedAt),
        payload=tostring(document.payload)
}

.alter table deviceLog policy update
@'[{"IsEnabled": true, "Source": "landing", "Query": "parseDeviceLog", "IsTransactional": true, "PropagateIngestionProperties": false}]'

.show ingestion failures 

landing
| limit 1
//| count

deviceLog
| count

deviceLog
| order by enqueuedTime desc
| limit 10

.show table deviceLog extents
